#include "keymap_common.h"
#include "keyboard_fn.h"

const uint8_t keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  KEYMAP(
    KC_ESC,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_BSPC, 
    KC_TAB,  KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_ENT, 
    KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_UP,   KC_SLSH, 
    KC_LCTL,          KC_LGUI, KC_LALT, KC_FN0,           KC_FN1,  KC_LEFT, KC_DOWN, KC_RGHT),

  KEYMAP(
    KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_EQL, 
    KC_BSPC, KC_4,    KC_5,    KC_6,    KC_NO,   KC_NO,   KC_UP,   KC_DOWN, KC_LEFT, KC_RGHT, KC_QUOT, KC_MINS, 
    KC_CAPS, KC_7,    KC_8,    KC_9,    KC_0,    KC_LBRC, KC_RBRC, KC_BSLS, KC_DOT,  KC_MSTP, KC_DEL, 
    KC_CALC,          KC_INS,  KC_LSFT, KC_NO,            KC_SPC,  KC_VOLD, KC_MUTE, KC_VOLU),

  KEYMAP(
    KC_FN6,  KC_FN7,  KC_FN8,  KC_FN9,  KC_FN10, KC_FN11, KC_FN12, KC_FN13, KC_FN14, KC_FN15, KC_FN16, KC_FN17, 
    KC_FN4,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_FN18, KC_FN19, 
    KC_FN3,  KC_F10,  KC_F11,  KC_F12,  KC_NO,   KC_FN20, KC_FN21, KC_FN22, KC_FN23, KC_PGUP, KC_APP, 
    KC_FN5,           KC_WSCH, KC_WREF, KC_SPC,           KC_NO,   KC_HOME, KC_PGDN, KC_END),

  KEYMAP(
    KC_FN2, KC_P7,   KC_P8,   KC_P9,   KC_PPLS, KC_PMNS, KC_NO,   KC_NO,   KC_NO,   KC_MINS, KC_EQL,  KC_BSPC, 
    KC_TAB,  KC_P4,   KC_P5,   KC_P6,   KC_PAST, KC_PSLS, KC_NO,   KC_LBRC, KC_RBRC, KC_SCLN, KC_QUOT, KC_ENT, 
    KC_LSFT, KC_P1,   KC_P2,   KC_P3,   KC_P0,   KC_PDOT, KC_COMM, KC_DOT,  KC_SLSH, KC_PGUP, KC_RSFT, 
    KC_LCTL,          KC_NLCK, KC_LALT, KC_SPC,           KC_SPC,  KC_LEFT, KC_DOWN, KC_RGHT),
};

const action_t fn_actions[] = {
  ACTION_LAYER_TAP_KEY(1, KC_SPC),
  ACTION_LAYER_TAP_KEY(2, KC_SPC),
  ACTION_LAYER_TOGGLE(0),
  ACTION_LAYER_TOGGLE(3),
  ACTION_FUNCTION_OPT(KEYBOARD_CONTROL, CONTROL_BOOTLOADER),
  ACTION_FUNCTION_OPT(KEYBOARD_CONTROL, CONTROL_SLEEP), // Fn5
  ACTION_MODS_KEY(MOD_LSFT, KC_GRV),
  ACTION_MODS_KEY(MOD_LSFT, KC_1),
  ACTION_MODS_KEY(MOD_LSFT, KC_2),
  ACTION_MODS_KEY(MOD_LSFT, KC_3),
  ACTION_MODS_KEY(MOD_LSFT, KC_4), // Fn10
  ACTION_MODS_KEY(MOD_LSFT, KC_5),
  ACTION_MODS_KEY(MOD_LSFT, KC_6),
  ACTION_MODS_KEY(MOD_LSFT, KC_7),
  ACTION_MODS_KEY(MOD_LSFT, KC_8),
  ACTION_MODS_KEY(MOD_LSFT, KC_9), // Fn15
  ACTION_MODS_KEY(MOD_LSFT, KC_0),
  ACTION_MODS_KEY(MOD_LSFT, KC_EQL),
  ACTION_MODS_KEY(MOD_LSFT, KC_QUOT),
  ACTION_MODS_KEY(MOD_LSFT, KC_MINS),
  ACTION_MODS_KEY(MOD_LSFT, KC_LBRC), // Fn20
  ACTION_MODS_KEY(MOD_LSFT, KC_RBRC),
  ACTION_MODS_KEY(MOD_LSFT, KC_BSLS),
  ACTION_MODS_KEY(MOD_LSFT, KC_DOT), // Fn23
};
