#include "keymap_common.h"
#include "keyboard_fn.h"

const uint8_t keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  KEYMAP(KC_LEFT, KC_RGHT, KC_FN0, KC_ESC),
  KEYMAP(KC_FN1, KC_FN2, KC_TRNS, KC_FN3),
};

const action_t fn_actions[] = {
  ACTION_LAYER_MOMENTARY(1),
  ACTION_FUNCTION_OPT(SWITCH_DEVICE, SWITCH_DEVICE_BLE_REBOND),
  ACTION_FUNCTION_OPT(KEYBOARD_CONTROL, CONTROL_BOOTLOADER),
  ACTION_FUNCTION_OPT(KEYBOARD_CONTROL, CONTROL_BATTERY_PERCENTAGE),
};
